### ISSUE TITLE
each closure grammar issue

### ISSUE THREAD

**Issue by ZZHHAANNGG** [wordlessj/Bamboo#1]
`[UIButton(), UIButton(), UIButton()].bb.each{ }`

**Unable to infer complex closure return type; add explicit type to disambiguate**

![image](https://user-images.githubusercontent.com/12008247/59469231-36ae9280-8e02-11e9-9977-669bb7b677f0.png)

**Comment by wordlessj** [comment]
`each()` takes a closure which expects a return type, so you shouldn't pass an empty closure to it. Look at the example in README.

```
[view1, view2, view3].bb.each {
    $0.bb.width(10)
}
```

**Comment by ZZHHAANNGG** [comment]
@wordlessj thanks
