### ISSUE TITLE
Did I misunderstand the usage of Bamboo?

### ISSUE THREAD

**Issue by ZZHHAANNGG** [wordlessj/Bamboo#2]
`
 view.pd.add(scrollView.pd.backgroundColor(UIColor.red))
  scrollView.pd.contentOffset(CGPoint(x: 0, y: -300)).object.bb.fill()
`
`scrollView.pd.add(`

`categoryButtonFactory().bb.width(115).height(92).center().item.pd.title("title1")`
`.action(action: { b in  }).backgroundColor(UIColor.red),`

`categoryButtonFactory().bb.width(115).height(92).centerX(-115).centerY().item.pd.title("title2")`
`.action(action: { b in }).backgroundColor(UIColor.gray),`

`categoryButtonFactory().bb.width(115).height(92).centerX(115).centerY().item.pd.title("title3")`
`.action(action: { b in }).backgroundColor(UIColor.green) )}`

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/12008247/59523276-da4d8080-8e9e-11e9-9391-f322cfed40d4.png">

**Comment by wordlessj** [comment]
You can't add constraints before the view is added to its superview. Put layout code after `pd.add()`.

**Comment by ZZHHAANNGG** [comment]
@wordlessj  thanks
